class TradingThresholds:
    # RSI threshold tiers
    RSI_OVERSOLD_EXTREME = 25.0
    RSI_OVERSOLD = 30.0
    RSI_OVERSOLD_MILD = 35.0
    RSI_OVERBOUGHT_MILD = 65.0
    RSI_OVERBOUGHT = 70.0

    # Score weights
    SCORE_BASELINE = 50
    RSI_SCORE_EXTREME_OVERSOLD = -15
    RSI_SCORE_OVERSOLD = -15
    RSI_SCORE_MILD_OVERSOLD = -10
    RSI_SCORE_OVERBOUGHT = 15
    RSI_SCORE_MILD_OVERBOUGHT = 10
    MACD_SCORE_GOLDEN_CROSS = -12
    MACD_SCORE_DEATH_CROSS = 12

    # Bollinger scoring
    BB_NARROW_BAND_WIDTH = 0.03
    BB_SCORE_BREAK_NARROW = -15
    BB_SCORE_BREAK_WIDE = -10
    BB_BREAK_DEPTH_MULTIPLIER_NARROW = 20
    BB_BREAK_DEPTH_MULTIPLIER_WIDE = 15
    BB_SCORE_BELOW_MIDDLE = -6
    BB_SCORE_ABOVE_MIDDLE = 6
    BB_SCORE_ABOVE_UPPER = 12

    # Entry context gating
    ENTRY_SETUP_MIN_STRONG = 2
    ENTRY_CONFIRM_MIN_STRONG = 2
    ENTRY_CORE_CONFIRM_MIN = 0
    ENTRY_SETUP_MIN_WEAK = 3
    ENTRY_CONFIRM_MIN_WEAK = 1
    ENTRY_CORE_CONFIRMATION_FLAGS = (
        "macd_stabilizing",
        "macd_contracting",
        "momentum_turn",
    )

    # Momentum confirmation
    MOMENTUM_TURN_ACCELERATION = 0.0
    SELLING_PRESSURE_EASING_ACCELERATION = -0.002
    SELLING_PRESSURE_EASING_CHANGE_PCT = 0.6
    MOMENTUM_TREND_UP_THRESHOLD = 0.1
    MOMENTUM_TREND_DOWN_THRESHOLD = -0.1

    # MACD adaptive confirmation thresholds
    MACD_STD_LOOKBACK_POINTS = 240
    MACD_STD_FLOOR = 0.12
    MACD_STABILIZING_STD_MULTIPLIER = -0.5
    MACD_CONTRACTING_STD_MULTIPLIER = 1.0

    # Trend thresholds
    TREND_THRESHOLD_MIN = 0.25
    TREND_THRESHOLD_MAX = 0.9
    TREND_THRESHOLD_BASE = 0.2
    TREND_THRESHOLD_PER_HOUR = 0.025

    # Signal dedup
    SIGNAL_DEDUP_MIN_WINDOW_SECONDS = 30 * 60
    SIGNAL_DEDUP_RELATIVE_TOLERANCE = 0.005
    SIGNAL_DEDUP_SCORE_TOLERANCE = 10

    # Falling-knife graded penalty
    FALLING_KNIFE_PENALTY_ENTRY_READY = 15
    FALLING_KNIFE_PENALTY_CONFIRMED = 30
    FALLING_KNIFE_PENALTY_UNCONFIRMED = 60
